#!/usr/bin/env python3
"""Generate an interior-cell mask in the same projection as the India SVG boundary."""

from __future__ import annotations

import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "assets/map-data/india.simplified.geo.json"
OUTPUT = ROOT / "lib/india-interior-mask.ts"
VIEW_WIDTH = 320.0
VIEW_HEIGHT = 380.0
PADDING = 15.0
CELL_SIZE = 6


def project(lon: float, lat: float) -> tuple[float, float]:
    x = math.radians(lon)
    bounded_lat = max(min(lat, 85.0), -85.0)
    y = math.log(math.tan(math.pi / 4.0 + math.radians(bounded_lat) / 2.0))
    return x, y


def exterior_rings(geometry: dict):
    geometry_type = geometry.get("type")
    coordinates = geometry.get("coordinates", [])
    if geometry_type == "Polygon" and coordinates:
        yield coordinates[0]
    elif geometry_type == "MultiPolygon":
        for polygon in coordinates:
            if polygon:
                yield polygon[0]
    elif geometry_type == "GeometryCollection":
        for member in geometry.get("geometries", []):
            yield from exterior_rings(member)


def point_in_ring(point: tuple[float, float], ring: list[tuple[float, float]]) -> bool:
    x, y = point
    inside = False
    previous = len(ring) - 1
    for current, (current_x, current_y) in enumerate(ring):
        previous_x, previous_y = ring[previous]
        intersects = ((current_y > y) != (previous_y > y)) and (x < (previous_x - current_x) * (y - current_y) / ((previous_y - current_y) or 1e-12) + current_x)
        if intersects:
            inside = not inside
        previous = current
    return inside


def main() -> None:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    geometries = [feature.get("geometry", {}) for feature in data.get("features", [])] if data.get("type") == "FeatureCollection" else [data.get("geometry", {}) if data.get("type") == "Feature" else data]
    raw_rings = [ring for geometry in geometries for ring in exterior_rings(geometry) if len(ring) >= 3]
    projected = [[project(lon, lat) for lon, lat in ring] for ring in raw_rings]
    all_points = [point for ring in projected for point in ring]
    min_x = min(point[0] for point in all_points)
    max_x = max(point[0] for point in all_points)
    min_y = min(point[1] for point in all_points)
    max_y = max(point[1] for point in all_points)
    scale = min((VIEW_WIDTH - PADDING * 2) / (max_x - min_x), (VIEW_HEIGHT - PADDING * 2) / (max_y - min_y))
    x_offset = (VIEW_WIDTH - (max_x - min_x) * scale) / 2.0
    y_offset = (VIEW_HEIGHT - (max_y - min_y) * scale) / 2.0
    rings = [[(x_offset + (x - min_x) * scale, y_offset + (max_y - y) * scale) for x, y in ring] for ring in projected]

    cells: list[int] = []
    offset = CELL_SIZE / 2
    for y in range(0, int(VIEW_HEIGHT), CELL_SIZE):
        for x in range(0, int(VIEW_WIDTH), CELL_SIZE):
            point = (x + offset, y + offset)
            if any(point_in_ring(point, ring) for ring in rings):
                cells.extend([x, y])

    numbers = ", ".join(map(str, cells))
    output = f'''// Generated by scripts/generate_india_interior_mask.py from the MIT-licensed\n// nswamy14/geoJson india.simplified.geo.json source.\n\nexport const INDIA_INTERIOR_CELL_SIZE = {CELL_SIZE};\nexport const INDIA_INTERIOR_CELLS = new Uint16Array([{numbers}]);\nexport const INDIA_INTERIOR_CELL_COUNT = {len(cells) // 2};\n'''
    OUTPUT.write_text(output, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(cells) // 2} cells.")


if __name__ == "__main__":
    main()
